/*
  # Add supervisor_alerts table

  ## Purpose
  Provides persistent storage for alerts generated by the DELTA (and other) supervisor bots.
  Previously all bot logs were localStorage-only and lost on refresh.

  ## New Tables
  - `supervisor_alerts`
    - `id` (uuid, primary key)
    - `bot_name` (text) — which bot fired the alert: ALPHA, BETA, GAMMA, DELTA
    - `alert_type` (text) — category e.g. fleet_spike, uninvoiced_trips, unusual_mileage
    - `message` (text) — human-readable alert description
    - `severity` (text) — info | warning | error
    - `resolved` (boolean) — whether dispatcher has acknowledged/resolved
    - `resolved_at` (timestamptz) — when it was resolved
    - `payload` (jsonb) — raw data that triggered the alert
    - `created_at` (timestamptz)

  ## Security
  - RLS enabled
  - Authenticated users can read, insert, and update alerts for their org
  - No org isolation needed here since this is an internal ops table used by admins/dispatchers
*/

CREATE TABLE IF NOT EXISTS supervisor_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bot_name text NOT NULL DEFAULT '',
  alert_type text NOT NULL DEFAULT '',
  message text NOT NULL DEFAULT '',
  severity text NOT NULL DEFAULT 'warning',
  resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamptz,
  payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE supervisor_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read supervisor alerts"
  ON supervisor_alerts FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert supervisor alerts"
  ON supervisor_alerts FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update supervisor alerts"
  ON supervisor_alerts FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE INDEX IF NOT EXISTS supervisor_alerts_bot_name_idx ON supervisor_alerts (bot_name);
CREATE INDEX IF NOT EXISTS supervisor_alerts_resolved_idx ON supervisor_alerts (resolved);
CREATE INDEX IF NOT EXISTS supervisor_alerts_created_at_idx ON supervisor_alerts (created_at DESC);
