export const PROVIDER_CATEGORIES = [
  { key: 'cloud', label: 'Cloud Infrastructure', color: '#f59e0b' },
  { key: 'communication', label: 'Communication', color: '#0ea5e9' },
  { key: 'payments', label: 'Payments', color: '#00e5a0' },
  { key: 'maps', label: 'Maps & Logistics', color: '#c9a84c' },
  { key: 'crm', label: 'CRM & Automation', color: '#a855f7' },
  { key: 'monitoring', label: 'Monitoring', color: '#ff4757' },
  { key: 'analytics', label: 'Analytics & Flags', color: '#8b5cf6' },
  { key: 'automation', label: 'QA & Automation', color: '#14b8a6' },
  { key: 'storage', label: 'Storage', color: '#64748b' },
];

export const STARTER_STACK = [
  {
    key: 'sentry_observability',
    name: 'Sentry App Monitoring',
    order: 1,
    category: 'monitoring',
    useFor: 'Track frontend crashes, API/function failures, slow routes, and production regressions.',
    installFirst: true,
    installUrl: 'https://vercel.com/marketplace/sentry',
    waitOn: ['Session Replay for every user', 'Source-map upload automation until your deploy flow is stable'],
  },
  {
    key: 'posthog',
    name: 'PostHog',
    order: 2,
    category: 'analytics',
    useFor: 'See where dispatchers, drivers, and companies drop off. Add session replay and feature flags later.',
    installFirst: true,
    installUrl: 'https://vercel.com/marketplace/posthog',
    waitOn: ['Feature flags for all features', 'Broad autocapture on every screen before your core UX is stable'],
  },
  {
    key: 'resend',
    name: 'Resend',
    order: 3,
    category: 'communication',
    useFor: 'Operational emails, onboarding emails, and account or business management emails.',
    installFirst: true,
    installUrl: 'https://vercel.com/marketplace/resend',
    waitOn: ['Marketing blasts', 'Complex email template system before your core transactional emails work'],
  },
  {
    key: 'checkly',
    name: 'Checkly',
    order: 4,
    category: 'monitoring',
    useFor: 'Watch login, /admin/sentry, /driver, and dispatch load after you stabilize core flows.',
    installFirst: false,
    installUrl: 'https://vercel.com/integrations/checkly',
    waitOn: ['Dozens of checks and noisy alerts before the important routes are stable'],
  },
  {
    key: 'slack',
    name: 'Slack',
    order: 5,
    category: 'communication',
    useFor: 'Send deploy failures, webhook failures, sandbox test failures, and security alerts to one ops channel.',
    installFirst: false,
    installUrl: 'https://vercel.com/integrations/slack',
    waitOn: ['Every low-signal notification', 'Multiple channels until you know what really matters'],
  },
  {
    key: 'browserbase',
    name: 'Browserbase',
    order: 6,
    category: 'automation',
    useFor: 'Later-phase AI QA bot, remote support bot, and browser automation for smoke tests and user support.',
    installFirst: false,
    installUrl: 'https://vercel.com/marketplace/browserbase',
    waitOn: ['Unsupervised browser agents in production', 'Automated patching before monitoring is reliable'],
  },
];

export const PROVIDER_REGISTRY = [
  {
    key: 'sentry_observability',
    name: 'Sentry App Monitoring',
    shortName: 'Sentry',
    category: 'monitoring',
    description: 'Capture frontend errors, function failures, route crashes, slow traces, and release regressions.',
    logoInitial: 'S',
    logoColor: '#8b5cf6',
    planRequired: 'free',
    fields: [
      { key: 'dsn', label: 'DSN', type: 'password', placeholder: 'https://...@o0.ingest.sentry.io/...' },
      { key: 'auth_token', label: 'Auth Token', type: 'password', placeholder: 'sntrys_...' },
      { key: 'org_slug', label: 'Organization Slug', type: 'text', placeholder: 'penthouse-dispatch' },
      { key: 'project_slug', label: 'Project Slug', type: 'text', placeholder: 'dispatch-web' },
      { key: 'environment', label: 'Environment', type: 'select', options: ['production', 'preview', 'development'] },
    ],
    docsUrl: 'https://vercel.com/marketplace/sentry',
  },
  {
    key: 'aws_sqs',
    name: 'AWS SQS',
    shortName: 'SQS',
    category: 'cloud',
    description: 'Amazon Simple Queue Service for reliable message queuing between platform services.',
    logoInitial: 'A',
    logoColor: '#f59e0b',
    planRequired: 'growth',
    fields: [
      { key: 'aws_access_key_id', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...' },
      { key: 'aws_secret_access_key', label: 'Secret Access Key', type: 'password', placeholder: 'Your AWS secret' },
      { key: 'aws_region', label: 'Region', type: 'text', placeholder: 'us-east-1' },
      { key: 'queue_url', label: 'Queue URL', type: 'text', placeholder: 'https://sqs.us-east-1.amazonaws.com/...' },
    ],
    docsUrl: 'https://aws.amazon.com/sqs/',
  },
  {
    key: 'aws_s3',
    name: 'AWS S3',
    shortName: 'S3',
    category: 'cloud',
    description: 'Amazon S3 for storing driver photos, trip documents, and export files.',
    logoInitial: 'A',
    logoColor: '#f59e0b',
    planRequired: 'growth',
    fields: [
      { key: 'aws_access_key_id', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...' },
      { key: 'aws_secret_access_key', label: 'Secret Access Key', type: 'password', placeholder: 'Your AWS secret' },
      { key: 'aws_region', label: 'Region', type: 'text', placeholder: 'us-east-1' },
      { key: 'bucket_name', label: 'Bucket Name', type: 'text', placeholder: 'my-dispatch-bucket' },
    ],
    docsUrl: 'https://aws.amazon.com/s3/',
  },
  {
    key: 'aws_sns',
    name: 'AWS SNS',
    shortName: 'SNS',
    category: 'cloud',
    description: 'Amazon SNS for push notifications and event fan-out to multiple subscribers.',
    logoInitial: 'A',
    logoColor: '#f59e0b',
    planRequired: 'enterprise',
    fields: [
      { key: 'aws_access_key_id', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...' },
      { key: 'aws_secret_access_key', label: 'Secret Access Key', type: 'password', placeholder: 'Your AWS secret' },
      { key: 'aws_region', label: 'Region', type: 'text', placeholder: 'us-east-1' },
      { key: 'topic_arn', label: 'Topic ARN', type: 'text', placeholder: 'arn:aws:sns:...' },
    ],
    docsUrl: 'https://aws.amazon.com/sns/',
  },
  {
    key: 'gcp_pubsub',
    name: 'Google Pub/Sub',
    shortName: 'Pub/Sub',
    category: 'cloud',
    description: 'Google Cloud Pub/Sub for asynchronous messaging and event streaming.',
    logoInitial: 'G',
    logoColor: '#0ea5e9',
    planRequired: 'growth',
    fields: [
      { key: 'project_id', label: 'Project ID', type: 'text', placeholder: 'my-gcp-project' },
      { key: 'service_account_json', label: 'Service Account JSON', type: 'textarea', placeholder: '{"type":"service_account",...}' },
      { key: 'topic_name', label: 'Topic Name', type: 'text', placeholder: 'dispatch-events' },
    ],
    docsUrl: 'https://cloud.google.com/pubsub',
  },
  {
    key: 'gcp_storage',
    name: 'Google Cloud Storage',
    shortName: 'GCS',
    category: 'cloud',
    description: 'Google Cloud Storage for scalable object storage and file management.',
    logoInitial: 'G',
    logoColor: '#0ea5e9',
    planRequired: 'growth',
    fields: [
      { key: 'project_id', label: 'Project ID', type: 'text', placeholder: 'my-gcp-project' },
      { key: 'service_account_json', label: 'Service Account JSON', type: 'textarea', placeholder: '{"type":"service_account",...}' },
      { key: 'bucket_name', label: 'Bucket Name', type: 'text', placeholder: 'my-dispatch-bucket' },
    ],
    docsUrl: 'https://cloud.google.com/storage',
  },
  {
    key: 'gcp_functions',
    name: 'Google Cloud Functions',
    shortName: 'GCF',
    category: 'cloud',
    description: 'Trigger serverless functions in response to dispatch events.',
    logoInitial: 'G',
    logoColor: '#0ea5e9',
    planRequired: 'enterprise',
    fields: [
      { key: 'project_id', label: 'Project ID', type: 'text', placeholder: 'my-gcp-project' },
      { key: 'service_account_json', label: 'Service Account JSON', type: 'textarea', placeholder: '{"type":"service_account",...}' },
      { key: 'function_url', label: 'Function URL', type: 'text', placeholder: 'https://us-central1-...' },
    ],
    docsUrl: 'https://cloud.google.com/functions',
  },
  {
    key: 'twilio',
    name: 'Twilio SMS',
    shortName: 'Twilio',
    category: 'communication',
    description: 'Send SMS notifications to drivers and riders for trip updates.',
    logoInitial: 'T',
    logoColor: '#e01f3d',
    planRequired: 'free',
    fields: [
      { key: 'account_sid', label: 'Account SID', type: 'text', placeholder: 'AC...' },
      { key: 'auth_token', label: 'Auth Token', type: 'password', placeholder: 'Your Twilio auth token' },
      { key: 'from_number', label: 'From Number', type: 'text', placeholder: '+1...' },
    ],
    docsUrl: 'https://www.twilio.com/docs/sms',
  },
  {
    key: 'resend',
    name: 'Resend',
    shortName: 'Resend',
    category: 'communication',
    description: 'Transactional email for onboarding, alerts, password help, invites, and account management.',
    logoInitial: 'R',
    logoColor: '#ff5f2e',
    planRequired: 'free',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 're_...' },
      { key: 'from_email', label: 'From Email', type: 'email', placeholder: 'ops@penthousedispatch.com' },
      { key: 'reply_to_email', label: 'Reply-To Email', type: 'email', placeholder: 'support@penthousedispatch.com' },
    ],
    docsUrl: 'https://vercel.com/marketplace/resend',
  },
  {
    key: 'sendgrid',
    name: 'SendGrid',
    shortName: 'SendGrid',
    category: 'communication',
    description: 'Transactional email for receipts, alerts, and weekly summaries.',
    logoInitial: 'S',
    logoColor: '#0ea5e9',
    planRequired: 'free',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'SG...' },
      { key: 'from_email', label: 'From Email', type: 'email', placeholder: 'dispatch@yourcompany.com' },
      { key: 'from_name', label: 'From Name', type: 'text', placeholder: 'Penthouse Dispatch' },
    ],
    docsUrl: 'https://docs.sendgrid.com/',
  },
  {
    key: 'slack',
    name: 'Slack',
    shortName: 'Slack',
    category: 'communication',
    description: 'Push bot alerts, dispatch summaries, and anomaly reports to Slack channels.',
    logoInitial: 'S',
    logoColor: '#611f69',
    planRequired: 'growth',
    fields: [
      { key: 'webhook_url', label: 'Incoming Webhook URL', type: 'text', placeholder: 'https://hooks.slack.com/services/...' },
      { key: 'channel', label: 'Default Channel', type: 'text', placeholder: '#dispatch-alerts' },
    ],
    docsUrl: 'https://api.slack.com/messaging/webhooks',
  },
  {
    key: 'stripe',
    name: 'Stripe',
    shortName: 'Stripe',
    category: 'payments',
    description: 'Process driver payouts, subscription billing, and invoicing.',
    logoInitial: 'S',
    logoColor: '#635bff',
    planRequired: 'free',
    fields: [
      { key: 'publishable_key', label: 'Publishable Key', type: 'text', placeholder: 'pk_...' },
      { key: 'secret_key', label: 'Secret Key', type: 'password', placeholder: 'sk_...' },
      { key: 'webhook_secret', label: 'Webhook Secret', type: 'password', placeholder: 'whsec_...' },
    ],
    docsUrl: 'https://stripe.com/docs',
  },
  {
    key: 'plaid',
    name: 'Plaid',
    shortName: 'Plaid',
    category: 'payments',
    description: 'Verify driver bank accounts and enable ACH bank transfers.',
    logoInitial: 'P',
    logoColor: '#00e5a0',
    planRequired: 'enterprise',
    fields: [
      { key: 'client_id', label: 'Client ID', type: 'text', placeholder: 'Your Plaid client ID' },
      { key: 'secret', label: 'Secret', type: 'password', placeholder: 'Your Plaid secret' },
      { key: 'environment', label: 'Environment', type: 'select', options: ['sandbox', 'development', 'production'] },
    ],
    docsUrl: 'https://plaid.com/docs/',
  },
  {
    key: 'google_maps',
    name: 'Google Maps',
    shortName: 'Maps',
    category: 'maps',
    description: 'Geocoding, route optimization, and real-time traffic for trip routing.',
    logoInitial: 'G',
    logoColor: '#4285f4',
    planRequired: 'free',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'Your Google Maps API key' },
    ],
    docsUrl: 'https://developers.google.com/maps',
  },
  {
    key: 'mapbox',
    name: 'Mapbox',
    shortName: 'Mapbox',
    category: 'maps',
    description: 'Custom map rendering and navigation with Mapbox GL for the live dispatch view.',
    logoInitial: 'M',
    logoColor: '#0ea5e9',
    planRequired: 'growth',
    fields: [
      { key: 'access_token', label: 'Access Token', type: 'password', placeholder: 'pk.eyJ...' },
      { key: 'style_url', label: 'Map Style URL (optional)', type: 'text', placeholder: 'mapbox://styles/...' },
    ],
    docsUrl: 'https://docs.mapbox.com/',
  },
  {
    key: 'here_maps',
    name: 'HERE Maps',
    shortName: 'HERE',
    category: 'maps',
    description: 'Enterprise-grade routing, ETA prediction, and fleet tracking via HERE APIs.',
    logoInitial: 'H',
    logoColor: '#00afaa',
    planRequired: 'enterprise',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'Your HERE API key' },
      { key: 'app_id', label: 'App ID (legacy)', type: 'text', placeholder: 'Optional legacy App ID' },
    ],
    docsUrl: 'https://developer.here.com/',
  },
  {
    key: 'posthog',
    name: 'PostHog',
    shortName: 'PostHog',
    category: 'analytics',
    description: 'Understand where users drop off, replay critical sessions, and add release flags later.',
    logoInitial: 'P',
    logoColor: '#f54e00',
    planRequired: 'growth',
    fields: [
      { key: 'project_api_key', label: 'Project API Key', type: 'password', placeholder: 'phc_...' },
      { key: 'host', label: 'Host', type: 'text', placeholder: 'https://us.i.posthog.com' },
      { key: 'autocapture', label: 'Autocapture', type: 'select', options: ['disabled', 'core-events-only', 'full'] },
      { key: 'feature_flags', label: 'Feature Flags', type: 'select', options: ['disabled', 'ready-later'] },
    ],
    docsUrl: 'https://vercel.com/marketplace/posthog',
  },
  {
    key: 'hubspot',
    name: 'HubSpot',
    shortName: 'HubSpot',
    category: 'crm',
    description: 'Sync company and contact data to HubSpot CRM for sales and onboarding.',
    logoInitial: 'H',
    logoColor: '#ff7a59',
    planRequired: 'growth',
    fields: [
      { key: 'access_token', label: 'Private App Token', type: 'password', placeholder: 'pat-na1-...' },
      { key: 'portal_id', label: 'Portal ID', type: 'text', placeholder: 'Your HubSpot portal ID' },
    ],
    docsUrl: 'https://developers.hubspot.com/',
  },
  {
    key: 'airtable',
    name: 'Airtable',
    shortName: 'Airtable',
    category: 'crm',
    description: 'Mirror dispatch data, driver records, and trip logs into Airtable bases.',
    logoInitial: 'A',
    logoColor: '#fcb400',
    planRequired: 'growth',
    fields: [
      { key: 'api_key', label: 'Personal Access Token', type: 'password', placeholder: 'patXXX...' },
      { key: 'base_id', label: 'Base ID', type: 'text', placeholder: 'appXXX...' },
    ],
    docsUrl: 'https://airtable.com/developers/',
  },
  {
    key: 'zapier',
    name: 'Zapier Webhooks',
    shortName: 'Zapier',
    category: 'crm',
    description: 'Trigger Zapier workflows from dispatch events via outbound webhooks.',
    logoInitial: 'Z',
    logoColor: '#ff4a00',
    planRequired: 'free',
    fields: [
      { key: 'webhook_url', label: 'Zapier Webhook URL', type: 'text', placeholder: 'https://hooks.zapier.com/...' },
    ],
    docsUrl: 'https://zapier.com/apps/webhooks/',
  },
  {
    key: 'checkly',
    name: 'Checkly',
    shortName: 'Checkly',
    category: 'monitoring',
    description: 'Synthetic checks for login, /admin/sentry, /driver, and your dispatch load path.',
    logoInitial: 'C',
    logoColor: '#5b8cff',
    planRequired: 'growth',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'Your Checkly API key' },
      { key: 'check_group', label: 'Check Group', type: 'text', placeholder: 'Penthouse Dispatch Core Routes' },
      { key: 'alert_email', label: 'Alert Email', type: 'email', placeholder: 'alerts@penthousedispatch.com' },
    ],
    docsUrl: 'https://vercel.com/integrations/checkly',
  },
  {
    key: 'pagerduty',
    name: 'PagerDuty',
    shortName: 'PagerDuty',
    category: 'monitoring',
    description: 'Escalate critical bot alerts and system failures to on-call PagerDuty teams.',
    logoInitial: 'P',
    logoColor: '#25c151',
    planRequired: 'enterprise',
    fields: [
      { key: 'integration_key', label: 'Events API v2 Integration Key', type: 'password', placeholder: 'Your routing key' },
      { key: 'service_name', label: 'Service Name', type: 'text', placeholder: 'Penthouse Dispatch' },
    ],
    docsUrl: 'https://developer.pagerduty.com/',
  },
  {
    key: 'browserbase',
    name: 'Browserbase',
    shortName: 'Browserbase',
    category: 'automation',
    description: 'Remote browser automation for future AI QA, support bots, smoke tests, and remote assist workflows.',
    logoInitial: 'B',
    logoColor: '#ff6b57',
    planRequired: 'enterprise',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'bb_live_...' },
      { key: 'project_id', label: 'Project ID', type: 'text', placeholder: 'proj_...' },
      { key: 'default_region', label: 'Region', type: 'select', options: ['us-west-2', 'us-east-1', 'eu-central-1'] },
    ],
    docsUrl: 'https://vercel.com/marketplace/browserbase',
  },
  {
    key: 'datadog',
    name: 'Datadog',
    shortName: 'Datadog',
    category: 'monitoring',
    description: 'Send platform metrics, bot performance data, and error events to Datadog.',
    logoInitial: 'D',
    logoColor: '#632ca6',
    planRequired: 'enterprise',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'Your Datadog API key' },
      { key: 'app_key', label: 'Application Key', type: 'password', placeholder: 'Your Datadog App key' },
      { key: 'site', label: 'Site', type: 'select', options: ['datadoghq.com', 'datadoghq.eu', 'us3.datadoghq.com'] },
    ],
    docsUrl: 'https://docs.datadoghq.com/',
  },
];

export const PLAN_TIERS = {
  free: { label: 'Free', color: '#00e5a0', order: 0 },
  growth: { label: 'Growth', color: '#c9a84c', order: 1 },
  enterprise: { label: 'Enterprise', color: '#f59e0b', order: 2 },
};
